services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - devcontainer.env
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    depends_on:
      - postgres

  postgres:
    image: postgres:16.2
    restart: unless-stopped
    env_file:
      - devcontainer.env
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes: 
      - postgres-data:/var/lib/postgresql/data

  pgAdmin:
    image: dpage/pgadmin4
    env_file:
      - devcontainer.env
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
  
volumes:
  postgres-data:
  pgadmin-data: